### ISSUE TITLE
GISLibrary host_functions.cpp should include <cassert>

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-100ExpertTeam/OpenS100#13]
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/62906211/664ad3b1-53f4-45ab-a10d-626da27aa054)

**Comment by gorogara** [comment]
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/5345308/f45dd4f4-ee4f-45c7-ad86-5ff6235c84bd)

I was unaware of this issue because some development environments did not require "caasert". Thanks.
