### ISSUE TITLE
Changes required to use latest S-101 portrayal catalog

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-100ExpertTeam/OpenS100#14]
The latest portrayal catalog uses non-integer viewing group values. Note that the S-100 portrayal catalog schema defines viewing groups as a subclass of `CatalogItem`. Catalog items are identified via type `s100Symbol:IdString`.

![image](https://github.com/S-100ExpertTeam/OpenS100/assets/62906211/d8103dc5-1b21-4559-877d-1a5b25c206a0)
 

The following changes are necessary to support the latest PC:

In ViewingGroup.h:
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/62906211/44b41ef8-8bbe-4d52-afba-324267062100)

In ViewingGroup.cpp:
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/62906211/eb8d6212-b6af-4202-9c91-d76e0ead67ea)

**Comment by gorogara** [comment]
I have deleted [int value] of [ViewingGroup] and will use the [id] of [CatalogItem].
Thanks for the detailed feedback.

In ViewingGroup.h:
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/5345308/d2c9a203-6b12-432e-bbb9-0dbb706d3f01)

In CatalogItem.h:
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/5345308/acb962fd-4835-4fe2-b232-6d05947b2cf0)
