### ISSUE TITLE
Feedback on installation manual

### ISSUE THREAD

**Issue by JinkiJung** [S-100ExpertTeam/OpenS100#15]
Hi, I've tried to build this application following your installation manual but there is something to be added there to make it compilable.

I needed to add one more packages, HDF5:

`vcpkg install HDF5:x64-windows`

and it requires Lua 5.1 DLL file (64bit) in the same folder with the executable to execute the viewer.

That was it! Thank you for your work on Open S100. 👍

**Comment by gorogara** [comment]
Thank you for your feedbacks. 

I updated the installation manual about vcpkg. 

The dll issue was being resolved by configuration like below. 
![image](https://github.com/S-100ExpertTeam/OpenS100/assets/5345308/53bcf689-c45d-40a1-919e-bcb5f8e56a68)

As you said, it is right to move the dll to the executable folder to run it alone.

**Comment by JinkiJung** [comment]
Thank you for your update! 😄
