### ISSUE TITLE
Missing some dependencies

### ISSUE THREAD

**Issue by JinkiJung** [S-100ExpertTeam/OpenS100#16]
Hi, my colleague found two dependencies missing in order to build the recent commit:

* libxml2:x64-windows
* libxslt:x64-windows

Could you update your vcpkg install guideline? 😊

**Comment by gorogara** [comment]
Hi, libxslt:x64-windows was added to the vcpkg install guideline.
libxslt is dependent on libxml2, so only need to add libxslt.
Thank you for your feed back.
