### ISSUE TITLE
Provide Binaries

### ISSUE THREAD

**Issue by cjmoeller** [S-100ExpertTeam/OpenS100#17]
Hi, 

It would be great if you could provide binaries and releases of OpenS100. Also, is it possible to build this project for Linux?

Kind regards

**Comment by dnwkfkwk** [comment]
Hi, 
You can download OpenS100 binary as current version. 
[OpenS100.zip](https://github.com/S-100ExpertTeam/OpenS100/files/12877155/OpenS100.zip)

If you have problem on execute OpenS100 binary then install vcregist (below link).
vcregist : https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

and OpenS100 is developed at windows, so it need some work to build for Linux.

**Comment by cjmoeller** [comment]
Thank you!
