### ISSUE TITLE
server/batch mode?

### ISSUE THREAD

**Issue by halset** [S-100ExpertTeam/OpenS100#22]
Can this be used in server- or batch mode on linux? So have a folder with the different feature/portrayal catalogues and another folder with some S-100 data and then call the app with options to create an image of a specific area in a specific projection and a specific size? So like a command line OGC WMS?

Such a functionality would be useful for including this software as a building block in a server side solution. Like a OGC WMS server, OGC API Maps server, a OGC WMTS server or such.

Perhaps that could attract more contributors as well.

**Comment by gorogara** [comment]
@halset 

1. Linux Support
It is only possible to build for Windows. 
Therefore, execution is guaranteed on Windows servers, but not on Linux servers.
I'm not sure if it's possible with tools like Wine. Testing is needed.
Ultimately, Linux support is necessary, but it is insufficient with the current staff.
It seems possible to start supporting some modules. (E.g: Feature catalogue, Portrayal Catalogue modules etc)
However, our team lacks knowledge of cross-platform development for Linux and Windows, so we need to secure the technology.

2. Command Line Support
We do not yet support the use of command line style.
Our idea is to create a command line project as open source project using OpenS100 as a Git Submodule.

3. WMS/WMTS Support
We developed a WMS server and tilemap production tool in the S-57 engine we developed before.
The WMS server was not for multiple users, just for testing.
As with #2, it should not be included in OpenS100, but it would be nice to have a separate open source using OpenS100 as a Git Submodule.

In the end, I couldn't give a positive answer to the question you asked. But, please keep watching OpenS100 project and contribute if possible.
