### ISSUE TITLE
Korean Project Folder Names

### ISSUE THREAD

**Issue by ufukakdag** [S-100ExpertTeam/OpenS100#4]
Is it possible to use only English alphabet characters when naming project folders? Korean alphabet characters makes it harder to grasp project structure. Thanks in advance...

**Comment by dnwkfkwk** [comment]
I try to use only English alphabetic characters.
However, it may still remain a Korean character.
In fact, I searched Korean, but I couldn't find it.
Please let me know where Korean was used to name the project folder.

**Comment by ufukakdag** [comment]
![korean_folder_names](https://user-images.githubusercontent.com/88457129/148778210-25c7869b-4fbf-4df2-8616-96eaa1c7da78.png)
I've added one sample for korean folder names case. This naming pattern is same for all sub-projects of OpenS100 (FeatureCatalog, GeeoMetryLibrary, GISLibrary, etc).

**Comment by dnwkfkwk** [comment]
Thank you for the information.
I thought those folders were automatically converted in English Windows into folders that are automatically created in Visual Studio. (resource files/source files/header files)
I will revise it and update it soon.

**Comment by ufukakdag** [comment]
Thank you for your attention!

**Comment by dnwkfkwk** [comment]
Folder names have been changed to English words.
Have a nice day!
