### ISSUE TITLE
All documents can be resaved with "Codepage 65001"

### ISSUE THREAD

**Issue by gtuna** [S-100ExpertTeam/OpenS100#8]
Unicode characters in files could not saved in the current codepage. Code pages do not have any support for UTF characters.

![ss0](https://user-images.githubusercontent.com/16979311/158766088-218c93a3-55f6-4314-887b-12945613de29.png)

All documents can be resaved with "Codepage 65001"

![ss2](https://user-images.githubusercontent.com/16979311/158765238-a9c789e2-f043-4baf-b24c-9f6ba0c39e74.png)

**Comment by gorogara** [comment]
There is no Unicode characters in current version of LibMFCUtil.h.

Please check it. 

We tried to erase all characters except English. 

![image](https://user-images.githubusercontent.com/5345308/158797881-7f83adf6-1897-4583-8aae-5bbec5ff70c4.png)

**Comment by gtuna** [comment]
Yes, you are right but when I try to write a comment with UTf-8 extended characters (e.g. in Turkish 'üğişöçIÜĞİŞÖÇI' )  VS gives a warning about codepages.

**Comment by gorogara** [comment]
This project support English only, please make comment in English.

**Comment by gtuna** [comment]
All right, thank you for your time.
